[2022-12-12 12:46:27,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:46:15.104986+00:00 [queued]>
[2022-12-12 12:46:27,217] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:46:15.104986+00:00 [queued]>
[2022-12-12 12:46:27,217] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:46:27,218] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 12:46:27,218] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:46:27,227] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): create_dataframe> on 2022-12-12 12:46:15.104986+00:00
[2022-12-12 12:46:27,233] {standard_task_runner.py:52} INFO - Started process 3263 to run task
[2022-12-12 12:46:27,236] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rates', 'create_dataframe', 'manual__2022-12-12T12:46:15.104986+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/load_rates.py', '--cfg-path', '/tmp/tmppnlh8d0d', '--error-file', '/tmp/tmpyz3a18fo']
[2022-12-12 12:46:27,236] {standard_task_runner.py:80} INFO - Job 15: Subtask create_dataframe
[2022-12-12 12:46:27,272] {task_command.py:369} INFO - Running <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:46:15.104986+00:00 [running]> on host 58259600a754
[2022-12-12 12:46:27,334] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rates
AIRFLOW_CTX_TASK_ID=create_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T12:46:15.104986+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T12:46:15.104986+00:00
[2022-12-12 12:46:27,335] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_rates.py", line 88, in create_dataframe
    rates = json.loads(rates)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2022-12-12 12:46:27,342] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rates, task_id=create_dataframe, execution_date=20221212T124615, start_date=20221212T124627, end_date=20221212T124627
[2022-12-12 12:46:27,350] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task create_dataframe (the JSON object must be str, bytes or bytearray, not dict; 3263)
[2022-12-12 12:46:27,367] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 12:46:27,405] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
