[2022-12-12 16:06:06,488] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.load_to_google_storage manual__2022-12-12T16:06:03.588744+00:00 [queued]>
[2022-12-12 16:06:06,495] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.load_to_google_storage manual__2022-12-12T16:06:03.588744+00:00 [queued]>
[2022-12-12 16:06:06,495] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:06:06,495] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 16:06:06,495] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:06:06,504] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): load_to_google_storage> on 2022-12-12 16:06:03.588744+00:00
[2022-12-12 16:06:06,510] {standard_task_runner.py:52} INFO - Started process 10218 to run task
[2022-12-12 16:06:06,512] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rates', 'load_to_google_storage', 'manual__2022-12-12T16:06:03.588744+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmpg6kt4b8s', '--error-file', '/tmp/tmppdgwfh9y']
[2022-12-12 16:06:06,513] {standard_task_runner.py:80} INFO - Job 43: Subtask load_to_google_storage
[2022-12-12 16:06:06,552] {task_command.py:369} INFO - Running <TaskInstance: load_rates.load_to_google_storage manual__2022-12-12T16:06:03.588744+00:00 [running]> on host 58259600a754
[2022-12-12 16:06:06,598] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rates
AIRFLOW_CTX_TASK_ID=load_to_google_storage
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T16:06:03.588744+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T16:06:03.588744+00:00
[2022-12-12 16:06:06,634] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 110, in load_to_google_storage
    storage_client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 128, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 268, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 546, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 539, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 219, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS], quota_project_id=quota_project_id
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 118, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File ServiceKey_GoogleCloud.json was not found.
[2022-12-12 16:06:06,641] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rates, task_id=load_to_google_storage, execution_date=20221212T160603, start_date=20221212T160606, end_date=20221212T160606
[2022-12-12 16:06:06,649] {standard_task_runner.py:97} ERROR - Failed to execute job 43 for task load_to_google_storage (File ServiceKey_GoogleCloud.json was not found.; 10218)
[2022-12-12 16:06:06,684] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 16:06:06,707] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
