[2022-12-30 12:47:53,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: insert_new_rates.dag3_extract_rates_dictionary manual__2022-12-30T12:47:50.502629+00:00 [queued]>
[2022-12-30 12:47:53,355] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: insert_new_rates.dag3_extract_rates_dictionary manual__2022-12-30T12:47:50.502629+00:00 [queued]>
[2022-12-30 12:47:53,355] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-30 12:47:53,356] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-30 12:47:53,356] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-30 12:47:53,364] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): dag3_extract_rates_dictionary> on 2022-12-30 12:47:50.502629+00:00
[2022-12-30 12:47:53,368] {standard_task_runner.py:52} INFO - Started process 3806 to run task
[2022-12-30 12:47:53,370] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'insert_new_rates', 'dag3_extract_rates_dictionary', 'manual__2022-12-30T12:47:50.502629+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/insert_new_rates.py', '--cfg-path', '/tmp/tmp0y38uxve', '--error-file', '/tmp/tmpyha4m7cf']
[2022-12-30 12:47:53,371] {standard_task_runner.py:80} INFO - Job 72: Subtask dag3_extract_rates_dictionary
[2022-12-30 12:47:53,403] {task_command.py:369} INFO - Running <TaskInstance: insert_new_rates.dag3_extract_rates_dictionary manual__2022-12-30T12:47:50.502629+00:00 [running]> on host 99c1092660ad
[2022-12-30 12:47:53,453] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=insert_new_rates
AIRFLOW_CTX_TASK_ID=dag3_extract_rates_dictionary
AIRFLOW_CTX_EXECUTION_DATE=2022-12-30T12:47:50.502629+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-30T12:47:50.502629+00:00
[2022-12-30 12:47:53,454] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_new_rates.py", line 49, in dag3_extract_rates_dictionary
    rates = extract_rates_dictionary(results)
  File "/opt/airflow/dags/python/Helper.py", line 60, in extract_rates_dictionary
    rates = data['rates']
KeyError: 'rates'
[2022-12-30 12:47:53,459] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=insert_new_rates, task_id=dag3_extract_rates_dictionary, execution_date=20221230T124750, start_date=20221230T124753, end_date=20221230T124753
[2022-12-30 12:47:53,466] {standard_task_runner.py:97} ERROR - Failed to execute job 72 for task dag3_extract_rates_dictionary ('rates'; 3806)
[2022-12-30 12:47:53,502] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-30 12:47:53,531] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
